---
deployment:
  tasks:
    - export NODE_ENV=production
    - npm install
    - ng build --configuration=production
    - /bin/cp -Rf dist/clivet/* $HOME/public_html/
    - /bin/rm -rf $HOME/public_html/.[!.]*
